name: Run download-data demo Hourly

on:
  # Runs every hour on the hour
  schedule:
    - cron: '0 * * * *'

jobs:
  run-specific-demo:
    name: Run specific demo on ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11, 3.12]

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      
      - name: Run the specific demo (non-Windows)
        run: |
          python demos/download_data.py
        if: matrix.os != 'windows-latest'
      
      - name: Run the specific demo (Windows)
        shell: pwsh
        run: |
          Push-Location demos
          python download_data.py
          Pop-Location
        if: matrix.os == 'windows-latest'
